output = "./public"

[modules]
fill_templates = { path = "./plugins/target/wasm32-wasi/debug/fill_templates.wasm" }

[[stages.stage]]
module = "fill_templates"
[[stages.stage.volumes]]
host = "./site/"
guest = "./"
[[stages.stage.volumes]]
host = "./site/public/"
guest = "./.html_output/"
