output = "./public"

[modules]
to_html = { path="./plugins/target/wasm32-wasi/debug/to_html.wasm" }
fill_templates = { path="./plugins/target/wasm32-wasi/debug/fill_templates.wasm" }

[[stages.stage]]
module = "to_html"
    [[stages.stage.volumes]]
    host = "./site/posts/"
    guest = "./"
    [[stages.stage.volumes]]
    host = "./site/public/"
    guest = "./.html_output/"

[[stages.stage]]
module = "fill_templates"
    [[stages.stage.volumes]]
    host = "./site/posts/"
    guest = "./"
    [[stages.stage.volumes]]
    host = "./site/templates/"
    guest = "./templates/"
    [[stages.stage.volumes]]
    host = "./site/public/"
    guest = "./.html_output/"
